import type { LucideIcon } from "lucide-react";
import {
  BadgeCheck,
  Brush,
  ChartNoAxesColumnIncreasing,
  Clapperboard,
  Download,
  Eraser,
  Expand,
  FileImage,
  FileSliders,
  ImageDown,
  Layers3,
  LayoutTemplate,
  MonitorSmartphone,
  Palette,
  PenTool,
  Presentation,
  ScanSearch,
  Sparkles,
  SwatchBook,
  WandSparkles,
} from "lucide-react";

export type SkillStoreCategory = "creative" | "editing" | "analysis" | "export";

export type SkillStoreItem = {
  id: string;
  name: string;
  category: SkillStoreCategory;
  subcategory: string;
  summary: string;
  capabilityPrompt: string;
  sourceRepo: string;
  sourceUrl: string;
  sourceScore: number;
  signal: "Stars" | "Release downloads" | "Template adoption";
  status: "已同步" | "待适配" | "内测";
  icon: LucideIcon;
  tags: string[];
  canvasSizes?: string[];
};

export const skillCategoryMeta: Record<SkillStoreCategory, {
  label: string;
  description: string;
  accent: string;
}> = {
  creative: {
    label: "创作型",
    description: "品牌套件、海报、Logo、PPT、视频脚本、网页视觉等生成流程。",
    accent: "oklch(0.68 0.18 210)",
  },
  editing: {
    label: "编辑型",
    description: "改图、换风格、重排版、去背景、扩图、修复和增强。",
    accent: "oklch(0.70 0.17 150)",
  },
  analysis: {
    label: "分析型",
    description: "分析品牌、竞品、用户意图、素材质量和设计完成度。",
    accent: "oklch(0.74 0.16 82)",
  },
  export: {
    label: "导出型",
    description: "按照常见社媒、电商、演示和广告画布尺寸批量生成。",
    accent: "oklch(0.67 0.19 330)",
  },
};

export const skillStoreItems: SkillStoreItem[] = [
  {
    id: "brand-kit-generator",
    name: "品牌套件生成器",
    category: "creative",
    subcategory: "品牌套件类",
    summary: "从品牌描述、截图或参考图提取色板、字体气质、图形语言和基础组件。",
    capabilityPrompt: "作为品牌套件生成 skill，请优先输出可用于品牌视觉系统的图像：包含色板、字体气质、Logo 使用方式、图形元素、社媒应用示例和设计规范感版式。",
    sourceRepo: "penpot/penpot",
    sourceUrl: "https://github.com/penpot/penpot",
    sourceScore: 36000,
    signal: "Stars",
    status: "已同步",
    icon: SwatchBook,
    tags: ["Brand kit", "Design system", "Tokens"],
  },
  {
    id: "poster-generator",
    name: "海报生成工作流",
    category: "creative",
    subcategory: "生成海报",
    summary: "根据主题、物料、活动信息和渠道规格生成多版海报构图。",
    capabilityPrompt: "作为海报生成 skill，请把用户提示词转成清晰海报主视觉：强调标题层级、主体画面、活动信息、CTA、安全边距和适合投放的视觉冲击力。",
    sourceRepo: "AUTOMATIC1111/stable-diffusion-webui",
    sourceUrl: "https://github.com/AUTOMATIC1111/stable-diffusion-webui",
    sourceScore: 150000,
    signal: "Stars",
    status: "已同步",
    icon: FileImage,
    tags: ["Poster", "Text to image", "Campaign"],
  },
  {
    id: "logo-exploration",
    name: "Logo 探索器",
    category: "creative",
    subcategory: "Logo",
    summary: "围绕品牌关键词生成字标、图标、徽章和极简符号方向。",
    capabilityPrompt: "作为 Logo 探索 skill，请生成品牌识别方向：包含简洁图标、字标比例、黑白可用性、可扩展图形语言和适合继续迭代的标志方案。",
    sourceRepo: "lllyasviel/Fooocus",
    sourceUrl: "https://github.com/lllyasviel/Fooocus",
    sourceScore: 44000,
    signal: "Stars",
    status: "已同步",
    icon: PenTool,
    tags: ["Logo", "Identity", "Variations"],
  },
  {
    id: "ppt-deck-builder",
    name: "PPT 页面生成器",
    category: "creative",
    subcategory: "PPT",
    summary: "把大纲转成封面、目录、章节页、图表页和总结页。",
    capabilityPrompt: "作为 PPT 页面生成 skill，请把用户内容转成演示文稿视觉：重视封面标题、信息分层、图表表达、章节节奏和 16:9 画布可读性。",
    sourceRepo: "gitbrent/PptxGenJS",
    sourceUrl: "https://github.com/gitbrent/PptxGenJS",
    sourceScore: 6000,
    signal: "Stars",
    status: "已同步",
    icon: Presentation,
    tags: ["Slides", "Deck", "PowerPoint"],
  },
  {
    id: "motion-script-writer",
    name: "视频脚本分镜",
    category: "creative",
    subcategory: "视频脚本",
    summary: "生成短视频脚本、镜头节奏、字幕节拍和可交付的分镜卡。",
    capabilityPrompt: "作为视频脚本分镜 skill，请把需求转成可视化分镜画面：包含镜头主体、运动节奏、字幕位置、开场钩子和竖屏/横屏封面图方向。",
    sourceRepo: "remotion-dev/remotion",
    sourceUrl: "https://github.com/remotion-dev/remotion",
    sourceScore: 21000,
    signal: "Stars",
    status: "已同步",
    icon: Clapperboard,
    tags: ["Storyboard", "Captions", "Motion"],
  },
  {
    id: "web-visual-composer",
    name: "网页视觉生成",
    category: "creative",
    subcategory: "网页视觉",
    summary: "生成首页首屏、产品区块、运营专题页和响应式视觉稿。",
    capabilityPrompt: "作为网页视觉生成 skill，请生成可落地的网页视觉稿：突出首屏主信息、产品展示、CTA、模块节奏、响应式布局和真实 UI 质感。",
    sourceRepo: "grapesjs/grapesjs",
    sourceUrl: "https://github.com/GrapesJS/grapesjs",
    sourceScore: 24000,
    signal: "Stars",
    status: "已同步",
    icon: MonitorSmartphone,
    tags: ["Web visual", "Landing page", "Responsive"],
  },
  {
    id: "whiteboard-visuals",
    name: "白板视觉草图",
    category: "creative",
    subcategory: "网页视觉",
    summary: "把粗略想法整理成流程图、草图、概念画布和协作白板。",
    capabilityPrompt: "作为白板视觉草图 skill，请把想法转成结构清晰的白板图：包含流程、模块、箭头关系、注释和可继续协作的低保真视觉。",
    sourceRepo: "excalidraw/excalidraw",
    sourceUrl: "https://github.com/excalidraw/excalidraw",
    sourceScore: 98000,
    signal: "Stars",
    status: "已同步",
    icon: LayoutTemplate,
    tags: ["Whiteboard", "Sketch", "Diagram"],
  },
  {
    id: "canvas-prototype",
    name: "交互画布原型",
    category: "creative",
    subcategory: "网页视觉",
    summary: "把 UI 想法转成可拖拽、可缩放、可批注的高保真画布。",
    capabilityPrompt: "作为交互画布原型 skill，请生成高保真产品画布：包含关键组件、状态、布局网格、交互提示和适合继续编辑的节点结构。",
    sourceRepo: "tldraw/tldraw",
    sourceUrl: "https://github.com/tldraw/tldraw",
    sourceScore: 38000,
    signal: "Stars",
    status: "内测",
    icon: Layers3,
    tags: ["Canvas", "Prototype", "Editor"],
  },
  {
    id: "layout-remix",
    name: "版式重排",
    category: "editing",
    subcategory: "重排版",
    summary: "保留原素材，把层级、对齐、留白和版心重新组织成多版。",
    capabilityPrompt: "作为版式重排 skill，请在保持原有内容意图的基础上优化构图、对齐、留白、标题层级和视觉平衡，生成新的排版方案。",
    sourceRepo: "konvajs/konva",
    sourceUrl: "https://github.com/konvajs/konva",
    sourceScore: 11000,
    signal: "Stars",
    status: "已同步",
    icon: LayoutTemplate,
    tags: ["Layout", "Canvas", "Composition"],
  },
  {
    id: "background-removal",
    name: "智能去背景",
    category: "editing",
    subcategory: "去背景",
    summary: "自动分割主体，输出透明底、白底、电商图和边缘精修版本。",
    capabilityPrompt: "作为智能去背景 skill，请优先处理主体分割与透明背景：保留主体边缘细节、头发/产品轮廓和干净 alpha，适合电商主图和设计合成。",
    sourceRepo: "danielgatis/rembg",
    sourceUrl: "https://github.com/danielgatis/rembg",
    sourceScore: 19000,
    signal: "Stars",
    status: "已同步",
    icon: Eraser,
    tags: ["Background removal", "Cutout", "Product"],
  },
  {
    id: "object-erase",
    name: "元素擦除修复",
    category: "editing",
    subcategory: "改图",
    summary: "移除画面中的文字、Logo、路人或杂物，并自然补全背景。",
    capabilityPrompt: "作为元素擦除修复 skill，请根据用户描述移除不需要的对象、文字或杂物，并自然补全背景、纹理、光影和透视。",
    sourceRepo: "Sanster/IOPaint",
    sourceUrl: "https://github.com/Sanster/IOPaint",
    sourceScore: 22000,
    signal: "Stars",
    status: "已同步",
    icon: WandSparkles,
    tags: ["Inpainting", "Cleanup", "Object removal"],
  },
  {
    id: "image-expansion",
    name: "画面扩图",
    category: "editing",
    subcategory: "扩图",
    summary: "把方图扩成横版、竖版或广告尺寸，延展背景并保护主体。",
    capabilityPrompt: "作为画面扩图 skill，请把现有画面自然延展到目标比例：保护原主体不变，补全环境、背景、光影和边缘细节。",
    sourceRepo: "Comfy-Org/ComfyUI",
    sourceUrl: "https://github.com/comfyanonymous/ComfyUI",
    sourceScore: 82000,
    signal: "Stars",
    status: "已同步",
    icon: Expand,
    tags: ["Outpaint", "Canvas", "Generative fill"],
  },
  {
    id: "style-transfer",
    name: "风格迁移",
    category: "editing",
    subcategory: "换风格",
    summary: "把参考风格应用到现有图片，生成摄影、插画、3D、国潮等方向。",
    capabilityPrompt: "作为风格迁移 skill，请把用户指定或参考图的风格迁移到画面：保持主体识别，同时调整材质、色调、笔触、光影和视觉流派。",
    sourceRepo: "lllyasviel/ControlNet",
    sourceUrl: "https://github.com/lllyasviel/ControlNet",
    sourceScore: 31000,
    signal: "Stars",
    status: "已同步",
    icon: Brush,
    tags: ["ControlNet", "Style", "Reference"],
  },
  {
    id: "image-upscale",
    name: "高清放大",
    category: "editing",
    subcategory: "改图",
    summary: "对低清素材进行超分、锐化和细节增强，适合海报和电商图。",
    capabilityPrompt: "作为高清放大 skill，请提升图片清晰度、细节、边缘和质感，同时避免过度锐化、假纹理和主体变形。",
    sourceRepo: "xinntao/Real-ESRGAN",
    sourceUrl: "https://github.com/xinntao/Real-ESRGAN",
    sourceScore: 28000,
    signal: "Stars",
    status: "已同步",
    icon: ImageDown,
    tags: ["Upscale", "Enhance", "Super resolution"],
  },
  {
    id: "face-restore",
    name: "人像修复增强",
    category: "editing",
    subcategory: "改图",
    summary: "修复人脸细节、提升清晰度，并适配证件照、海报人像和直播封面。",
    capabilityPrompt: "作为人像修复增强 skill，请改善人像清晰度、肤色、五官细节和光影自然度，同时保持身份一致和真实质感。",
    sourceRepo: "TencentARC/GFPGAN",
    sourceUrl: "https://github.com/TencentARC/GFPGAN",
    sourceScore: 36000,
    signal: "Stars",
    status: "已同步",
    icon: Sparkles,
    tags: ["Portrait", "Restore", "Face"],
  },
  {
    id: "brand-analyzer",
    name: "品牌视觉分析",
    category: "analysis",
    subcategory: "分析品牌",
    summary: "读取品牌素材，输出定位、颜色、字体、构图、竞品差异和设计禁区。",
    capabilityPrompt: "作为品牌视觉分析 skill，请先分析品牌定位、色彩、字体、构图、受众和禁区，再把分析转为可执行的视觉生成建议。",
    sourceRepo: "openai/CLIP",
    sourceUrl: "https://github.com/openai/CLIP",
    sourceScore: 25000,
    signal: "Stars",
    status: "已同步",
    icon: ScanSearch,
    tags: ["Brand analysis", "Vision", "Semantics"],
  },
  {
    id: "competitor-visual-audit",
    name: "竞品视觉扫描",
    category: "analysis",
    subcategory: "分析竞品",
    summary: "比较竞品站点、广告和社媒图，提炼视觉机会和差异化方向。",
    capabilityPrompt: "作为竞品视觉扫描 skill，请基于用户描述分析竞品视觉套路、差异机会、信息层级和可借鉴但不抄袭的创作方向。",
    sourceRepo: "microsoft/playwright",
    sourceUrl: "https://github.com/microsoft/playwright",
    sourceScore: 69000,
    signal: "Stars",
    status: "已同步",
    icon: ChartNoAxesColumnIncreasing,
    tags: ["Competitor", "Screenshot", "Audit"],
  },
  {
    id: "user-intent-parser",
    name: "用户需求解析",
    category: "analysis",
    subcategory: "分析用户输入",
    summary: "把自然语言需求拆成场景、受众、尺寸、风格、素材和交付要求。",
    capabilityPrompt: "作为用户需求解析 skill，请把用户提示词拆解成场景、受众、主体、尺寸、风格、素材、约束和最终生图提示词。",
    sourceRepo: "microsoft/TypeChat",
    sourceUrl: "https://github.com/microsoft/TypeChat",
    sourceScore: 8000,
    signal: "Stars",
    status: "已同步",
    icon: FileSliders,
    tags: ["Intent", "Structured prompt", "Brief"],
  },
  {
    id: "design-quality-check",
    name: "设计质量检查",
    category: "analysis",
    subcategory: "检查设计质量",
    summary: "检查对齐、层级、对比度、溢出、低清素材、文字可读性和安全区。",
    capabilityPrompt: "作为设计质量检查 skill，请先审查画面目标、层级、对齐、对比、可读性、安全区和素材质量，再给出可执行修改并生成优化版本。",
    sourceRepo: "pa11y/pa11y",
    sourceUrl: "https://github.com/pa11y/pa11y",
    sourceScore: 3500,
    signal: "Stars",
    status: "已同步",
    icon: BadgeCheck,
    tags: ["Quality", "Accessibility", "Contrast"],
  },
  {
    id: "prompt-safety-review",
    name: "生成提示词审阅",
    category: "analysis",
    subcategory: "分析用户输入",
    summary: "提前发现提示词歧义、缺尺寸、缺主体、版权风险和不可执行描述。",
    capabilityPrompt: "作为生成提示词审阅 skill，请先修正用户提示词中的歧义、缺失、版权风险和不可执行要求，再形成稳定可生图的提示词。",
    sourceRepo: "guardrails-ai/guardrails",
    sourceUrl: "https://github.com/guardrails-ai/guardrails",
    sourceScore: 4500,
    signal: "Stars",
    status: "内测",
    icon: ScanSearch,
    tags: ["Prompt", "Safety", "Validation"],
  },
  {
    id: "design-system-audit",
    name: "设计系统一致性",
    category: "analysis",
    subcategory: "检查设计质量",
    summary: "检查页面是否符合品牌 token、组件用法、间距、圆角和字体规范。",
    capabilityPrompt: "作为设计系统一致性 skill，请让输出符合统一 token、组件边界、间距、圆角、字体、颜色和页面结构规范。",
    sourceRepo: "storybookjs/storybook",
    sourceUrl: "https://github.com/storybookjs/storybook",
    sourceScore: 86000,
    signal: "Stars",
    status: "已同步",
    icon: Palette,
    tags: ["Design system", "Components", "Tokens"],
  },
  {
    id: "social-size-pack",
    name: "社媒全尺寸套件",
    category: "export",
    subcategory: "社媒平台尺寸",
    summary: "一键生成 Instagram、TikTok、YouTube、Facebook、X、小红书常用尺寸。",
    capabilityPrompt: "作为社媒全尺寸套件 skill，请按常见社媒画布适配输出，确保主体安全区、标题可读、裁切友好，并优先考虑 1:1、9:16、16:9 和横幅版本。",
    sourceRepo: "sharp/sharp",
    sourceUrl: "https://github.com/lovell/sharp",
    sourceScore: 30000,
    signal: "Stars",
    status: "已同步",
    icon: Download,
    tags: ["Resize", "Social", "Batch export"],
    canvasSizes: ["1080x1080", "1080x1920", "1920x1080", "1200x628"],
  },
  {
    id: "xiaohongshu-pack",
    name: "小红书封面套件",
    category: "export",
    subcategory: "社媒平台尺寸",
    summary: "生成小红书竖版封面、方图、长图和多图封面安全区。",
    capabilityPrompt: "作为小红书封面套件 skill，请生成适合小红书封面的视觉：强标题、竖版构图、封面点击率、笔记感排版和移动端安全区。",
    sourceRepo: "jimp-dev/jimp",
    sourceUrl: "https://github.com/jimp-dev/jimp",
    sourceScore: 14000,
    signal: "Stars",
    status: "已同步",
    icon: FileImage,
    tags: ["Xiaohongshu", "Cover", "Safe area"],
    canvasSizes: ["1242x1660", "1080x1440", "1080x1080"],
  },
  {
    id: "instagram-pack",
    name: "Instagram 尺寸套件",
    category: "export",
    subcategory: "社媒平台尺寸",
    summary: "生成 Feed、Story、Reels、Carousel 和广告投放图。",
    capabilityPrompt: "作为 Instagram 尺寸套件 skill，请生成适合 Feed、Story、Reels 和 Carousel 的视觉，兼顾移动端比例、主体居中和品牌曝光。",
    sourceRepo: "image-js/image-js",
    sourceUrl: "https://github.com/image-js/image-js",
    sourceScore: 3500,
    signal: "Stars",
    status: "已同步",
    icon: MonitorSmartphone,
    tags: ["Instagram", "Story", "Carousel"],
    canvasSizes: ["1080x1080", "1080x1350", "1080x1920"],
  },
  {
    id: "tiktok-pack",
    name: "TikTok/抖音尺寸套件",
    category: "export",
    subcategory: "社媒平台尺寸",
    summary: "生成竖屏视频封面、直播封面、信息流广告和商品卡尺寸。",
    capabilityPrompt: "作为 TikTok/抖音尺寸套件 skill，请生成竖屏优先的封面或信息流视觉：主体大、钩子强、文字短、移动端可读。",
    sourceRepo: "ffmpegwasm/ffmpeg.wasm",
    sourceUrl: "https://github.com/ffmpegwasm/ffmpeg.wasm",
    sourceScore: 13000,
    signal: "Stars",
    status: "已同步",
    icon: Clapperboard,
    tags: ["TikTok", "Douyin", "Video cover"],
    canvasSizes: ["1080x1920", "720x1280", "1080x1080"],
  },
  {
    id: "youtube-pack",
    name: "YouTube 频道套件",
    category: "export",
    subcategory: "社媒平台尺寸",
    summary: "生成缩略图、频道横幅、Shorts 封面和社区贴图。",
    capabilityPrompt: "作为 YouTube 频道套件 skill，请生成强点击缩略图、频道横幅或 Shorts 封面，重视主体表情/产品、标题大字和 16:9/9:16 裁切。",
    sourceRepo: "transloadit/uppy",
    sourceUrl: "https://github.com/transloadit/uppy",
    sourceScore: 30000,
    signal: "Stars",
    status: "已同步",
    icon: FileImage,
    tags: ["YouTube", "Thumbnail", "Banner"],
    canvasSizes: ["1280x720", "2560x1440", "1080x1920"],
  },
  {
    id: "ecommerce-pack",
    name: "电商主图套件",
    category: "export",
    subcategory: "电商平台尺寸",
    summary: "生成 1:1 主图、3:4 详情封面、白底图、透明底和活动图。",
    capabilityPrompt: "作为电商主图套件 skill，请生成平台友好的商品视觉：主体清晰、卖点明确、白底/场景图可选、文字不过载并适合主图审核。",
    sourceRepo: "imgproxy/imgproxy",
    sourceUrl: "https://github.com/imgproxy/imgproxy",
    sourceScore: 9500,
    signal: "Stars",
    status: "内测",
    icon: FileSliders,
    tags: ["E-commerce", "Product", "Marketplace"],
    canvasSizes: ["800x800", "1000x1000", "750x1000", "1200x1200"],
  },
  {
    id: "ad-platform-pack",
    name: "广告投放尺寸套件",
    category: "export",
    subcategory: "广告尺寸",
    summary: "生成 Meta、Google Display、信息流和横幅广告常用画布。",
    capabilityPrompt: "作为广告投放尺寸套件 skill，请生成可投放广告视觉：强主张、清晰 CTA、品牌露出、安全边距和多尺寸裁切一致性。",
    sourceRepo: "bannerbear/bannerbear-js",
    sourceUrl: "https://github.com/Bannerbear/bannerbear-js",
    sourceScore: 500,
    signal: "Template adoption",
    status: "已同步",
    icon: Download,
    tags: ["Ads", "Display", "Campaign"],
    canvasSizes: ["1200x628", "1080x1080", "300x250", "728x90", "160x600"],
  },
  {
    id: "presentation-export-pack",
    name: "演示交付套件",
    category: "export",
    subcategory: "PPT/演示尺寸",
    summary: "把画布导出为 16:9、4:3、A4 PDF 和演讲封面图。",
    capabilityPrompt: "作为演示交付套件 skill，请把画面适配为演示场景：16:9 可读、标题层级稳定、留白足够，并适合导出 PPT/PDF。",
    sourceRepo: "marp-team/marp",
    sourceUrl: "https://github.com/marp-team/marp",
    sourceScore: 8500,
    signal: "Stars",
    status: "已同步",
    icon: Presentation,
    tags: ["Presentation", "PDF", "Deck"],
    canvasSizes: ["1920x1080", "1024x768", "2480x3508"],
  },
  {
    id: "asset-compression-pack",
    name: "素材压缩交付",
    category: "export",
    subcategory: "全品类导出",
    summary: "按 PNG、JPG、WebP、透明图和轻量预览图批量压缩导出。",
    capabilityPrompt: "作为素材压缩交付 skill，请优先生成清晰、轻量、可导出的视觉资产，兼顾 PNG/JPG/WebP 交付、透明背景和预览缩略图需求。",
    sourceRepo: "imagemin/imagemin",
    sourceUrl: "https://github.com/imagemin/imagemin",
    sourceScore: 5400,
    signal: "Stars",
    status: "已同步",
    icon: FileSliders,
    tags: ["Compression", "WebP", "Delivery"],
    canvasSizes: ["Original", "2x", "1x", "Preview"],
  },
];

export const skillStoreStats = {
  total: skillStoreItems.length,
  synced: skillStoreItems.filter((skill) => skill.status === "已同步").length,
  source: "GitHub public popularity snapshot",
};

export type PendingSkillLoad = {
  id: string;
  name: string;
  category: SkillStoreCategory;
  categoryLabel: string;
  subcategory: string;
  summary: string;
  capabilityPrompt: string;
  sourceRepo: string;
  sourceUrl: string;
  tags: string[];
  canvasSizes?: string[];
  loadedAt: string;
};

export const PENDING_SKILL_LOAD_KEY = "artx:pending-skill-load";

export function createPendingSkillLoad(skill: SkillStoreItem): PendingSkillLoad {
  return {
    id: skill.id,
    name: skill.name,
    category: skill.category,
    categoryLabel: skillCategoryMeta[skill.category].label,
    subcategory: skill.subcategory,
    summary: skill.summary,
    capabilityPrompt: skill.capabilityPrompt,
    sourceRepo: skill.sourceRepo,
    sourceUrl: skill.sourceUrl,
    tags: skill.tags,
    canvasSizes: skill.canvasSizes,
    loadedAt: new Date().toISOString(),
  };
}

export function buildSkillPromptContext(skill: PendingSkillLoad) {
  return [
    `当前已加载 Skill：${skill.name}`,
    `分类：${skill.categoryLabel} / ${skill.subcategory}`,
    `能力说明：${skill.summary}`,
    `执行规则：${skill.capabilityPrompt}`,
    skill.canvasSizes?.length ? `优先适配尺寸：${skill.canvasSizes.join("、")}` : "",
    skill.tags.length ? `关键词：${skill.tags.join("、")}` : "",
  ].filter(Boolean).join("\n");
}
