import type { LucideIcon } from "lucide-react";
import {
  BadgeCheck,
  Brush,
  Camera,
  Clapperboard,
  FileImage,
  Frame,
  Globe2,
  Grid3x3,
  Images,
  MonitorSmartphone,
  Network,
  Newspaper,
  Palette,
  PenTool,
  PencilLine,
  PieChart,
  Presentation,
  Scissors,
  Shapes,
  Smile,
  Sparkle,
  Spline,
  Stamp,
  SwatchBook,
} from "lucide-react";

export type SkillStoreCategory =
  | "brand_system"
  | "logo_identity"
  | "landing_page"
  | "commerce_poster"
  | "product_visual"
  | "video_storyboard"
  | "image_editing"
  | "visual_audit"
  | "graphic_design"
  | "infographic"
  | "ui_design"
  | "office_visual"
  | "diagram"
  | "photo_art";

export type SkillStoreItem = {
  id: string;
  name: string;
  category: SkillStoreCategory;
  subcategory: string;
  summary: string;
  capability: "text_to_image" | "image_edit";
  capabilityPrompt: string;
  sourceRepo: string;
  sourceUrl: string;
  sourceScore: number;
  signal: "Stars" | "Release downloads" | "Template adoption";
  status: "已同步" | "待适配" | "内测";
  icon: LucideIcon;
  tags: string[];
  canvasSizes?: string[];
};

export const skillCategoryMeta: Record<SkillStoreCategory, {
  label: string;
  description: string;
  accent: string;
}> = {
  brand_system: {
    label: "品牌系统",
    description: "品牌色、字体气质、设计 token、组件规范和应用样张。",
    accent: "oklch(0.68 0.18 210)",
  },
  logo_identity: {
    label: "Logo 识别",
    description: "Logo、字标、徽章、品牌符号和识别方向探索。",
    accent: "oklch(0.70 0.19 300)",
  },
  landing_page: {
    label: "产品页 / 落地页",
    description: "首页首屏、产品页、营销页和响应式网页视觉。",
    accent: "oklch(0.70 0.16 155)",
  },
  commerce_poster: {
    label: "电商海报 / 社媒",
    description: "活动海报、商品主图、社媒封面和营销 Banner。",
    accent: "oklch(0.73 0.18 55)",
  },
  product_visual: {
    label: "产品视觉",
    description: "商品摄影、商业渲染、白底图、场景图和卖点视觉。",
    accent: "oklch(0.66 0.17 25)",
  },
  video_storyboard: {
    label: "视频活动 / 分镜",
    description: "短视频脚本、镜头节奏、分镜卡和活动视频封面。",
    accent: "oklch(0.67 0.19 330)",
  },
  image_editing: {
    label: "局部编辑 / 改图",
    description: "去背景、擦除、扩图、换风格、修复和局部重绘。",
    accent: "oklch(0.72 0.16 185)",
  },
  visual_audit: {
    label: "视觉分析 / 质检",
    description: "参考图分析、竞品拆解、提示词审阅和设计质量检查。",
    accent: "oklch(0.74 0.16 82)",
  },
  graphic_design: {
    label: "平面设计 / 视觉表达",
    description: "艺术海报、社媒图文、知识漫画和概念视觉表达。",
    accent: "oklch(0.69 0.19 275)",
  },
  infographic: {
    label: "信息图 / 数据可视化",
    description: "数据信息图、流程说明图、对比图表和统计图视觉。",
    accent: "oklch(0.66 0.17 235)",
  },
  ui_design: {
    label: "UI 界面视觉",
    description: "界面视觉稿、组件质感、设计系统样张和交互状态。",
    accent: "oklch(0.71 0.16 168)",
  },
  office_visual: {
    label: "办公配图",
    description: "文章配图、封面图、演示幻灯片和数据汇报视觉。",
    accent: "oklch(0.73 0.15 40)",
  },
  diagram: {
    label: "流程图 / 图示",
    description: "流程图、架构图、思维导图、泳道图和示意图。",
    accent: "oklch(0.68 0.16 200)",
  },
  photo_art: {
    label: "图像创意",
    description: "照片艺术化与创意风格：针织、速写、拼贴、印章档案、复古印刷和吉祥物。",
    accent: "oklch(0.7 0.17 330)",
  },
};

export const skillStoreItems: SkillStoreItem[] = [
  {
    id: "brand-system-kit",
    name: "品牌系统生成",
    category: "brand_system",
    subcategory: "品牌套件 / Design tokens",
    summary: "把品牌描述、产品定位或参考风格转成完整品牌系统板，包含色板、字体气质、图形语言和应用样张。",
    capability: "text_to_image",
    capabilityPrompt: "作为品牌系统生成 skill，请输出专业品牌 kit 视觉板：包含品牌定位、主色/辅助色/中性色、字体气质、Logo 使用区、图形元素、组件气质和至少三种应用示例。",
    sourceRepo: "penpot + style-dictionary + storybook",
    sourceUrl: "https://github.com/penpot/penpot",
    sourceScore: 145748,
    signal: "Stars",
    status: "已同步",
    icon: SwatchBook,
    tags: ["Brand kit", "Design tokens", "Identity"],
  },
  {
    id: "logo-identity-lab",
    name: "Logo 品牌识别",
    category: "logo_identity",
    subcategory: "Logo / 字标 / 品牌符号",
    summary: "围绕品牌关键词生成多方向 Logo 探索板，覆盖符号、字标、徽章、黑白可用性和推荐方向。",
    capability: "text_to_image",
    capabilityPrompt: "作为 Logo 品牌识别 skill，请生成 4 到 6 个可比较的标志方向：简洁、可缩放、黑白可用、避免商标抄袭，并说明每个方向的形态逻辑。",
    sourceRepo: "fooocus + diffusers + controlnet",
    sourceUrl: "https://github.com/lllyasviel/Fooocus",
    sourceScore: 118221,
    signal: "Stars",
    status: "已同步",
    icon: PenTool,
    tags: ["Logo", "Wordmark", "Symbol"],
  },
  {
    id: "landing-page-visual",
    name: "产品页落地页视觉",
    category: "landing_page",
    subcategory: "网页视觉 / 产品页",
    summary: "把产品、服务或活动需求生成真实可落地的网页首屏、产品页或多区块落地页视觉稿。",
    capability: "text_to_image",
    capabilityPrompt: "作为产品页落地页视觉 skill，请生成真实 UI 视觉：突出产品/服务首屏信号、模块层级、CTA、响应式布局、真实组件质感和可读文本区域。",
    sourceRepo: "grapesjs + shadcn/ui + tailwindcss",
    sourceUrl: "https://github.com/GrapesJS/grapesjs",
    sourceScore: 238597,
    signal: "Stars",
    status: "已同步",
    icon: MonitorSmartphone,
    tags: ["Landing page", "Web visual", "Responsive"],
    canvasSizes: ["1440x1024", "390x844", "1920x1080"],
  },
  {
    id: "commerce-poster-social",
    name: "电商海报社媒视觉",
    category: "commerce_poster",
    subcategory: "海报 / 社媒 / 营销图",
    summary: "根据产品、活动、优惠和渠道生成高冲击海报、商品主图、社媒封面和投放素材。",
    capability: "text_to_image",
    capabilityPrompt: "作为电商海报社媒视觉 skill，请生成商业可用主视觉：主体突出、标题区清晰、CTA 和品牌位明确，并适配方图/竖图/横幅裁切。",
    sourceRepo: "automatic1111 + comfyui + diffusers",
    sourceUrl: "https://github.com/AUTOMATIC1111/stable-diffusion-webui",
    sourceScore: 315310,
    signal: "Stars",
    status: "已同步",
    icon: FileImage,
    tags: ["Poster", "Campaign", "Social"],
    canvasSizes: ["1080x1080", "1080x1920", "1200x628"],
  },
  {
    id: "cross-border-commerce-agent",
    name: "跨境电商视觉 Agent",
    category: "commerce_poster",
    subcategory: "跨境平台 / 市场包 / 风险检查",
    summary: "按国家地区、平台、广告位、品类和模板组合商品图生成上下文，并在生成前检查文化、宗教、政治与 IP 风险。",
    capability: "text_to_image",
    capabilityPrompt: "作为跨境电商视觉 Agent，请先锁定市场、平台、广告位尺寸、安全区、品类模板和风险规则；图片只保留标题/卖点/价格/CTA 可编辑区域，不把价格、折扣、功效、认证或法律声明直接烘焙进画面。",
    sourceRepo: "ArtX market package registry + seller-center docs",
    sourceUrl: "https://sellercentral.amazon.com/help/hub/reference/G1881",
    sourceScore: 20260712,
    signal: "Template adoption",
    status: "内测",
    icon: Globe2,
    tags: ["Cross-border", "Marketplace", "Risk", "Template"],
    canvasSizes: ["2000x2000", "1080x1920", "1200x628"],
  },
  {
    id: "product-photography",
    name: "产品视觉商品摄影",
    category: "product_visual",
    subcategory: "商品摄影 / 产品渲染",
    summary: "生成商品摄影、商业渲染、白底主图、生活方式场景和卖点视觉，让产品清晰可检查。",
    capability: "text_to_image",
    capabilityPrompt: "作为产品视觉商品摄影 skill，请生成清晰商品主视觉：保持产品身份、材质、比例和卖点，匹配摄影灯光、表面、阴影、背景和商业质感。",
    sourceRepo: "comfyui + controlnet + diffusers",
    sourceUrl: "https://github.com/Comfy-Org/ComfyUI",
    sourceScore: 185461,
    signal: "Stars",
    status: "已同步",
    icon: Camera,
    tags: ["Product", "Photography", "Packshot"],
    canvasSizes: ["1000x1000", "1200x1600", "1920x1080"],
  },
  {
    id: "video-storyboard",
    name: "视频活动分镜",
    category: "video_storyboard",
    subcategory: "短视频 / 分镜 / 封面",
    summary: "把活动、广告或产品卖点转成连续分镜卡，包含镜头节奏、字幕位置、场景推进和封面方向。",
    capability: "text_to_image",
    capabilityPrompt: "作为视频活动分镜 skill，请生成 4 到 8 张连续分镜卡：开场钩子、主体展示、利益点、证明镜头和结尾 CTA，并标注镜头运动与字幕区。",
    sourceRepo: "remotion + diffusers + comfyui workflows",
    sourceUrl: "https://github.com/remotion-dev/remotion",
    sourceScore: 202147,
    signal: "Stars",
    status: "已同步",
    icon: Clapperboard,
    tags: ["Storyboard", "Video", "Keyframes"],
    canvasSizes: ["1080x1920", "1920x1080", "1280x720"],
  },
  {
    id: "image-local-edit",
    name: "局部编辑改图",
    category: "image_editing",
    subcategory: "去背景 / 擦除 / 扩图 / 换风格",
    summary: "对已有图片执行去背景、擦除、局部重绘、扩图、风格迁移和质量修复，并尽量保持未编辑区域不变。",
    capability: "image_edit",
    capabilityPrompt: "作为局部编辑改图 skill，请只修改用户指定区域或意图：保留主体身份、比例、未编辑像素、产品几何和文字位置，补全自然光影、纹理和透视。",
    sourceRepo: "rembg + iopaint + controlnet",
    sourceUrl: "https://github.com/danielgatis/rembg",
    sourceScore: 80589,
    signal: "Stars",
    status: "已同步",
    icon: Brush,
    tags: ["Inpaint", "Outpaint", "Background"],
  },
  {
    id: "visual-reference-audit",
    name: "视觉参考分析质检",
    category: "visual_audit",
    subcategory: "参考分析 / 竞品拆解 / 质量检查",
    summary: "分析参考图、竞品视觉和用户提示词，提炼可迁移的风格原则，并生成更完整、更干净的视觉方向。",
    capability: "text_to_image",
    capabilityPrompt: "作为视觉参考分析质检 skill，请先把用户输入或参考方向转成明确视觉诊断，再生成优化后的画面：提高层级、对齐、对比、可读性、安全区和风格一致性。",
    sourceRepo: "clip + llava + playwright",
    sourceUrl: "https://github.com/openai/CLIP",
    sourceScore: 149956,
    signal: "Stars",
    status: "已同步",
    icon: BadgeCheck,
    tags: ["Visual audit", "Reference", "Quality"],
  },
  {
    id: "art-poster-design",
    name: "艺术海报设计",
    category: "graphic_design",
    subcategory: "海报 / 概念视觉",
    summary: "围绕单一概念生成艺术化海报：一个想法、一种构图装置、严格的三层字级和刻意的留白。",
    capability: "text_to_image",
    capabilityPrompt: "作为艺术海报设计 skill，请只表达一个核心想法，选定一种构图装置（主图配字、字即图、破格网格或居中留白），层级不超过三层，保留大面积留白，主标题要能在远距离读出。",
    sourceRepo: "fooocus + penpot + diffusers",
    sourceUrl: "https://github.com/lllyasviel/Fooocus",
    sourceScore: 118221,
    signal: "Stars",
    status: "已同步",
    icon: Brush,
    tags: ["Poster", "Typography", "Concept"],
    canvasSizes: ["1080x1440", "1080x1920", "1600x1200"],
  },
  {
    id: "knowledge-comic",
    name: "知识漫画",
    category: "graphic_design",
    subcategory: "漫画 / 概念解释",
    summary: "把一个概念画成 4 到 8 格短漫画：开场用场景提问题，中段展示机制，结尾给出结论或行动。",
    capability: "text_to_image",
    capabilityPrompt: "作为知识漫画 skill，请生成 4 到 8 格连续漫画：第一格用场景呈现问题，中间展示机制而不是靠旁白，最后一格给出结论；角色、配色、线宽必须跨格一致。",
    sourceRepo: "p5.js + excalidraw + tldraw",
    sourceUrl: "https://github.com/excalidraw/excalidraw",
    sourceScore: 102000,
    signal: "Stars",
    status: "内测",
    icon: PenTool,
    tags: ["Comic", "Storyboard", "Explain"],
    canvasSizes: ["1200x1600", "1080x1080", "1600x900"],
  },
  {
    id: "xhs-carousel-images",
    name: "小红书轮播图",
    category: "graphic_design",
    subcategory: "社媒图文 / 轮播",
    summary: "把一条内容拆成封面加内页的完整轮播：统一版式系统、缩略图可读的封面、单页单观点和收尾页。",
    capability: "text_to_image",
    capabilityPrompt: "作为小红书轮播图 skill，请生成封面加 4 到 8 张内页：封面标题要在缩略图尺寸下可读，每页只讲一个观点，页边距/标题位/页脚位跨页完全一致，整套只用一个强调色。",
    sourceRepo: "penpot + tailwindcss + reveal.js",
    sourceUrl: "https://github.com/penpot/penpot",
    sourceScore: 145748,
    signal: "Stars",
    status: "已同步",
    icon: Images,
    tags: ["Xiaohongshu", "Carousel", "Social"],
    canvasSizes: ["1080x1440", "1242x1660", "1080x1080"],
  },
  {
    id: "infographic-designer",
    name: "信息图设计",
    category: "infographic",
    subcategory: "信息图 / 数据说明",
    summary: "把数据、流程或概念转成单张可读信息图：版式由数据形态决定，层级清楚，数字带单位和时间范围。",
    capability: "text_to_image",
    capabilityPrompt: "作为信息图设计 skill，请根据数据形态选定版式（竖向流程、对比分栏、时间轴、循环、金字塔、矩阵网格或数字主视觉），建立单一阅读顺序和清晰层级，每个数字都要带单位与时间范围。",
    sourceRepo: "observable plot + vega-lite + d3",
    sourceUrl: "https://github.com/vega/vega-lite",
    sourceScore: 76000,
    signal: "Stars",
    status: "已同步",
    icon: PieChart,
    tags: ["Infographic", "Data", "Layout"],
    canvasSizes: ["1080x1920", "1600x1200", "1080x1080"],
  },
  {
    id: "ui-visual-mockup",
    name: "界面视觉稿",
    category: "ui_design",
    subcategory: "UI 视觉 / 组件质感",
    summary: "生成去掉 AI 味的界面视觉稿：真实内容密度、统一设计系统、明确主操作和对齐到网格的排版。",
    capability: "text_to_image",
    capabilityPrompt: "作为界面视觉稿 skill，请生成生产级界面视觉：拒绝紫蓝渐变、全局玻璃拟态和 emoji 图标，使用真实内容密度与完整文案，主操作唯一，严格对齐到单一网格。",
    sourceRepo: "shadcn/ui + tailwindcss + storybook",
    sourceUrl: "https://github.com/shadcn-ui/ui",
    sourceScore: 238597,
    signal: "Stars",
    status: "已同步",
    icon: MonitorSmartphone,
    tags: ["UI", "Mockup", "Design system"],
    canvasSizes: ["1440x1024", "390x844", "1920x1080"],
  },
  {
    id: "article-illustrator",
    name: "文章配图",
    category: "office_visual",
    subcategory: "文章配图 / 插图",
    summary: "为具体文章生成配图：只画最难用文字说清的那一处，视觉语言全篇统一，语气匹配文章调性。",
    capability: "text_to_image",
    capabilityPrompt: "作为文章配图 skill，请先找准文章中最难用文字说清的那个点再画，视觉说明论点而不是标题名词，全篇保持同一媒介与配色逻辑，除信息性标签外不加字。",
    sourceRepo: "excalidraw + p5.js + diffusers",
    sourceUrl: "https://github.com/p5js/p5.js",
    sourceScore: 62000,
    signal: "Stars",
    status: "已同步",
    icon: Newspaper,
    tags: ["Illustration", "Editorial", "Article"],
    canvasSizes: ["1600x900", "1200x800", "1080x1080"],
  },
  {
    id: "cover-image-lab",
    name: "封面图设计",
    category: "office_visual",
    subcategory: "封面图 / 缩略图",
    summary: "生成全尺寸与缩略图双可读的封面：单一焦点、缩略图可读标题、预留标题安全区、情绪匹配内容。",
    capability: "text_to_image",
    capabilityPrompt: "作为封面图设计 skill，请先按缩略图尺寸定标题字级与元素数量，只保留一个焦点，为叠加标题预留干净区域，并自查清晰度/层级/缩略图可读性/情绪/品牌一致性五项。",
    sourceRepo: "fooocus + penpot + comfyui",
    sourceUrl: "https://github.com/Comfy-Org/ComfyUI",
    sourceScore: 185461,
    signal: "Stars",
    status: "已同步",
    icon: Frame,
    tags: ["Cover", "Thumbnail", "Title zone"],
    canvasSizes: ["1600x900", "1080x1080", "1280x720"],
  },
  {
    id: "slide-deck-visual",
    name: "演示幻灯片配图",
    category: "office_visual",
    subcategory: "演示 / 汇报配图",
    summary: "生成成套幻灯片视觉：固定版心与标题位，一页一个观点，标题写成结论，数据页只放一张图加一句洞察。",
    capability: "text_to_image",
    capabilityPrompt: "作为演示幻灯片配图 skill，请先给出页级规划（页码/版式/一句话内容），固定画布与标题位，一页只讲一个观点，标题写成结论而非标签，数据页只有一张图加一句洞察。",
    sourceRepo: "reveal.js + libreoffice + observable plot",
    sourceUrl: "https://github.com/hakimel/reveal.js",
    sourceScore: 68000,
    signal: "Stars",
    status: "已同步",
    icon: Presentation,
    tags: ["Slide", "Deck", "Presentation"],
    canvasSizes: ["1920x1080", "1280x720", "1080x1440"],
  },
  {
    id: "diagram-flowchart",
    name: "流程图架构图",
    category: "diagram",
    subcategory: "流程图 / 架构图 / 思维导图",
    summary: "把流程、架构或概念渲染成单张清晰图示：形状承载语义、连线正交少交叉、按层或角色用色、网格对齐。",
    capability: "text_to_image",
    capabilityPrompt: "作为流程图架构图 skill，请按内容选定图示类型（流程/架构/思维导图/泳道），保证唯一入口与出口，形状语义一致，连线正交且尽量少交叉，决策分支必须带条件标签。",
    sourceRepo: "mermaid + excalidraw + tldraw",
    sourceUrl: "https://github.com/mermaid-js/mermaid",
    sourceScore: 78000,
    signal: "Stars",
    status: "已同步",
    icon: Network,
    tags: ["Flowchart", "Architecture", "Mind map"],
    canvasSizes: ["1920x1080", "1600x900", "1080x1440"],
  },
  {
    id: "photo-organic-knit",
    name: "毛线针织海报",
    category: "photo_art",
    subcategory: "照片转毛线 / 钩针 / 手作海报",
    summary: "把照片重塑成手工毛线针织艺术海报：保留主体轮廓，材质换成针织、钩针、毛圈与羊毛毡，暖象牙色留白。需先上传一张照片作为参考图。",
    capability: "text_to_image",
    capabilityPrompt: "作为毛线针织海报 skill，请把参考照片或描述的主体重新编织成手工毛线艺术海报：主体徽章约占画面宽度 55-60%，四周留暖象牙色空白，针脚松紧不一、带线头，禁止塑料/黏土质感、矢量硬边和铺满全画面。",
    sourceRepo: "ArtX 图像创意",
    sourceUrl: "",
    sourceScore: 58,
    signal: "Stars",
    status: "已同步",
    icon: Spline,
    tags: ["Knit", "Crochet", "Handmade"],
    canvasSizes: ["1080x1440", "1440x1080", "1080x1080"],
  },
  {
    id: "photo-travel-sketch",
    name: "针管笔旅行速写",
    category: "photo_art",
    subcategory: "照片转旅行速写 / 针管笔 / 马克笔",
    summary: "把旅行照片转成 10-15 分钟现场速写：黑色针管笔松散线条、干马克笔点色，至少一半纸面留白。需先上传一张照片作为参考图。",
    capability: "text_to_image",
    capabilityPrompt: "作为针管笔旅行速写 skill，请把照片画成现场速写：暖白纸面，1 个视觉锚点加 2-3 个次要体块、细节不超过 5 处；黑色针管笔线条自然游走不封口，干马克笔分笔上色且偏灰，至少 45% 纸面不上色；禁止水彩晕染、尺规直线、重复窗格、文字和本子/桌面样机。",
    sourceRepo: "ArtX 图像创意",
    sourceUrl: "",
    sourceScore: 9,
    signal: "Stars",
    status: "已同步",
    icon: PencilLine,
    tags: ["Sketch", "Fineliner", "Travel"],
    canvasSizes: ["1440x1080", "1080x1440"],
  },
  {
    id: "surreal-pop-collage",
    name: "超现实波普拼贴",
    category: "photo_art",
    subcategory: "照片转波普拼贴 / 超现实",
    summary: "主体转黑白作为现实锚点，背景换成 2-3 块取自原图的大面积平涂色块，再加一个超现实巨物和一串渐变大小的小元素。需先上传一张照片作为参考图。",
    capability: "text_to_image",
    capabilityPrompt: "作为超现实波普拼贴 skill，请把主体处理成黑白照片作为现实锚点，背景替换为 2-3 块取自原图色彩的大面积哑光平涂色块，加入且只加入一个来自场景或当地文化的超现实巨大元素，再沿弧线排布 3-5 个大小递减的小元素和 2-3 笔白色手绘涂鸦；无渐变、无 3D 阴影、无文字水印，默认 3:4。",
    sourceRepo: "ArtX 图像创意",
    sourceUrl: "",
    sourceScore: 324,
    signal: "Stars",
    status: "已同步",
    icon: Shapes,
    tags: ["Pop art", "Collage", "Surreal"],
    canvasSizes: ["1080x1440", "1080x1080"],
  },
  {
    id: "photo-stamp-archive",
    name: "照片图章档案",
    category: "photo_art",
    subcategory: "照片 + 印章 / 档案排版",
    summary: "左侧原样保留照片，右侧暖白纸面盖一枚按主体造型的做旧印章，配打字机体档案标题，大面积留白。需先上传一张照片作为参考图。",
    capability: "text_to_image",
    capabilityPrompt: "作为照片图章档案 skill，请输出横版拼接：左侧约 55% 原样保留照片（不得改动），右侧约 45% 暖白纸面，拼缝笔直；纸面约 70% 留白，印章与说明组占约 30% 并靠一角；印章外形跟随主体（圆/方/山脊全景/拱形/剪影），带干墨、网点和套色错位；打字机体 1-3 词大写标题加小写副标题用 / 分隔。",
    sourceRepo: "ArtX 图像创意",
    sourceUrl: "",
    sourceScore: 361,
    signal: "Stars",
    status: "已同步",
    icon: Stamp,
    tags: ["Stamp", "Archive", "Typewriter"],
    canvasSizes: ["1920x1080", "1600x900"],
  },
  {
    id: "washi-tape-collage",
    name: "和纸胶带拼贴",
    category: "photo_art",
    subcategory: "照片转胶带拼贴 / 手作",
    summary: "用半透明和纸胶带在纸上重新拼出主体，胶带叠压透光，保留 1-3 个辨识锚点，大量留白。需先上传一张照片作为参考图。",
    capability: "text_to_image",
    capabilityPrompt: "作为和纸胶带拼贴 skill，请用撕边的半透明和纸胶带在纸面上重新拼出主体，胶带叠压处要透色，只保留 1-3 个辨识锚点并大量留白，不要还原人脸五官身份；若用户要求保留原照片，则按 3:4 画面左右约 50/50 并置原照片与胶带拼贴。",
    sourceRepo: "ArtX 图像创意",
    sourceUrl: "",
    sourceScore: 110,
    signal: "Stars",
    status: "已同步",
    icon: Scissors,
    tags: ["Washi tape", "Collage", "Paper craft"],
    canvasSizes: ["1080x1440", "1080x1080"],
  },
  {
    id: "pulp-print-poster",
    name: "高彩印刷海报",
    category: "photo_art",
    subcategory: "复古电影海报 / 高彩平印",
    summary: "90 年代通俗电影海报风：单一高饱和底色、主体压成硬边高反差色块、金黄色粗压缩大写标题和小字演职员块。",
    capability: "text_to_image",
    capabilityPrompt: "作为高彩印刷海报 skill，请做 90 年代通俗电影海报风：一个高饱和平涂底色，主体压成硬边高反差色块，金黄色（#F2B610）粗体压缩大写标题，底部一小块描述画面的演职员式小字，做旧纸张颗粒，全画面 3-4 色，默认 2:3；禁止出现真实电影、演员或片厂名称。",
    sourceRepo: "ArtX 图像创意",
    sourceUrl: "",
    sourceScore: 12,
    signal: "Stars",
    status: "已同步",
    icon: Newspaper,
    tags: ["Pulp", "Movie poster", "Print"],
    canvasSizes: ["1080x1620", "1080x1440"],
  },
  {
    id: "halftone-dot-poster",
    name: "像素印刷海报",
    category: "photo_art",
    subcategory: "点阵网点 / 单色印刷海报",
    summary: "3:4 竖版，主体由细密位图/网点点阵构成，单色或双色油墨印在暖色纸上，可选小标题。",
    capability: "text_to_image",
    capabilityPrompt: "作为像素印刷海报 skill，请输出 3:4 竖版海报：主体完全由细密的位图/网点点阵构成，单色或双色油墨印在暖色纸张上，可选标题或微型排版占画面 5-18%；这不是复古游戏像素画，禁止粗大像素块和霓虹色。",
    sourceRepo: "ArtX 图像创意",
    sourceUrl: "",
    sourceScore: 149,
    signal: "Stars",
    status: "已同步",
    icon: Grid3x3,
    tags: ["Halftone", "Bitmap", "Riso"],
    canvasSizes: ["1080x1440"],
  },
  {
    id: "minimal-zine-poster",
    name: "极简纸刊海报",
    category: "photo_art",
    subcategory: "独立杂志 / 诗意留白海报",
    summary: "诗意纸质感独立杂志海报：大面积留白，一个小型编辑拼贴焦点，实验性排版加一个点缀色。",
    capability: "text_to_image",
    capabilityPrompt: "作为极简纸刊海报 skill，请做竖版独立杂志风海报：纸张肌理与大面积留白，画面只放一个小尺度的编辑拼贴或焦点元素，实验性但克制的排版，全画面只用一个点缀色；有参考照片时按用户要求决定是改造它、参考它还是嵌入它。",
    sourceRepo: "ArtX 图像创意",
    sourceUrl: "",
    sourceScore: 7228,
    signal: "Stars",
    status: "已同步",
    icon: Sparkle,
    tags: ["Zine", "Editorial", "Minimal"],
    canvasSizes: ["1080x1440", "1080x1620"],
  },
  {
    id: "xiaohei-object-scenes",
    name: "小黑实物场景",
    category: "photo_art",
    subcategory: "小人 + 实物 / 叙事插画",
    summary: "一个黑色小人与真实物件互动，做出一个物理动作，配简短中文标注，纯白底留出叙事空白。",
    capability: "text_to_image",
    capabilityPrompt: "作为小黑实物场景 skill，请画一个纯黑色简笔小人（小黑）与真实质感的日常物件互动，完成一个明确的物理动作（推、爬、拉、躲、搬），配 1-3 处简短中文手写标注，纯白 #FFFFFF 背景并留出叙事空白；默认 16:9，用户要求长卷时改为超宽生活线。",
    sourceRepo: "ArtX 图像创意",
    sourceUrl: "",
    sourceScore: 532,
    signal: "Stars",
    status: "已同步",
    icon: Smile,
    tags: ["Character", "Real object", "Narrative"],
    canvasSizes: ["1920x1080", "2560x1080"],
  },
  {
    id: "ip-mascot-logo",
    name: "IP 吉祥物 Logo",
    category: "photo_art",
    subcategory: "吉祥物 / 应用图标 Logo",
    summary: "用 4-7 个大块基础形状搭出可爱 IP 角色作为 Logo，32×32 仍可辨认，2 个 IP 色 + 1 个纯色底，从画面一角探出。",
    capability: "text_to_image",
    capabilityPrompt: "作为 IP 吉祥物 Logo skill，请用 4-7 个大块基础几何形状搭出一个可爱的吉祥物角色，缩到 32×32 仍能辨认；只用 2 个 IP 色加 1 个略降饱和的纯色背景，1:1 画面，角色从左下或右下角探出、占满 85-95%，不要居中；无文字、无边框、无 3D，只保留极轻微的新拟物立体感。",
    sourceRepo: "ArtX 图像创意",
    sourceUrl: "",
    sourceScore: 5720,
    signal: "Stars",
    status: "已同步",
    icon: Palette,
    tags: ["Mascot", "Logo", "App icon"],
    canvasSizes: ["1024x1024"],
  },
];

export const skillStoreStats = {
  total: skillStoreItems.length,
  synced: skillStoreItems.filter((skill) => skill.status === "已同步").length,
  source: "Open-source MD documentation snapshot",
};

export type PendingSkillLoad = {
  id: string;
  name: string;
  category: SkillStoreCategory;
  categoryLabel: string;
  subcategory: string;
  summary: string;
  capability: SkillStoreItem["capability"];
  capabilityPrompt: string;
  sourceRepo: string;
  sourceUrl: string;
  tags: string[];
  canvasSizes?: string[];
  loadedAt: string;
};

export const PENDING_SKILL_LOAD_KEY = "artx:pending-skill-load";

export function createPendingSkillLoad(skill: SkillStoreItem): PendingSkillLoad {
  return {
    id: skill.id,
    name: skill.name,
    category: skill.category,
    categoryLabel: skillCategoryMeta[skill.category].label,
    subcategory: skill.subcategory,
    summary: skill.summary,
    capability: skill.capability,
    capabilityPrompt: skill.capabilityPrompt,
    sourceRepo: skill.sourceRepo,
    sourceUrl: skill.sourceUrl,
    tags: skill.tags,
    canvasSizes: skill.canvasSizes,
    loadedAt: new Date().toISOString(),
  };
}

export function buildSkillPromptContext(skill: PendingSkillLoad) {
  return [
    `当前已加载 Skill：${skill.name}`,
    `分类：${skill.categoryLabel} / ${skill.subcategory}`,
    `生成能力：${skill.capability === "image_edit" ? "图片编辑，需要用户提供参考图或画布图片" : "文生图，可直接根据提示词生成画面"}`,
    `能力说明：${skill.summary}`,
    `执行规则：${skill.capabilityPrompt}`,
    skill.canvasSizes?.length ? `优先适配尺寸：${skill.canvasSizes.join("、")}` : "",
    skill.tags.length ? `关键词：${skill.tags.join("、")}` : "",
  ].filter(Boolean).join("\n");
}
