// Generated from research/ai-visual-category-dataset-20260710/dataset-links.csv.
// Public link-only reference metadata. Do not put credentials or private URLs here.

import type { RawInspirationReference } from "./inspiration-references";

export const RAW_INSPIRATION_REFERENCES: RawInspirationReference[] = [
  {
    "id": "promptbase-001",
    "group": "行业品类",
    "subcategory": "服装",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/retro-chenille-embroidery-patch-studios",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FhKbxVk7KEzwBbExsrn7S%2Fresized%2F1782724981063n_500x500.webp",
    "title": "Retro Chenille Embroidery Patch Studios",
    "prompt": "Retro Chenille Embroidery Patch Studios",
    "stylePromptEn": "Retro Chenille Embroidery Patch Studios",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-002",
    "group": "品牌商业",
    "subcategory": "营销活动",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/retro-summer-posters",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FgqHDR3E2Fa819EiFKO8b%2Fresized%2F1781725055372s_500x500.webp",
    "title": "Retro Summer Posters",
    "prompt": "Retro Summer Posters",
    "stylePromptEn": "Retro Summer Posters",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-003",
    "group": "品牌商业",
    "subcategory": "营销活动",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/retro-minimalist-travel-art-posters-2",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FWeKxYBqGw4PIjkCw2MW8%2Fresized%2F1781768323612o_500x500.webp",
    "title": "Retro Minimalist Travel Art Posters",
    "prompt": "Retro Minimalist Travel Art Posters",
    "stylePromptEn": "Retro Minimalist Travel Art Posters",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-004",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/dreamy-contemporary-surreal-art-prints",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2Fv7pkPK4s0DX3AG5Jp2GN%2Fresized%2F1781463395404i_500x500.webp",
    "title": "Dreamy Contemporary Surreal Art Prints",
    "prompt": "Dreamy Contemporary Surreal Art Prints",
    "stylePromptEn": "Dreamy Contemporary Surreal Art Prints",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-005",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/distorted-cinematic-photos-of-carnivals",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FYKaKRQzYgBjoIS0PhGI3%2Fresized%2F1781286730845a_500x500.webp",
    "title": "Distorted Cinematic Photos",
    "prompt": "Distorted Cinematic Photos",
    "stylePromptEn": "Distorted Cinematic Photos",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-006",
    "group": "品牌商业",
    "subcategory": "营销活动",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/minimal-editorial-object-posters",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FnQ8P8rx42Pn5cqd00aok%2Fresized%2F1781017570349_500x500.webp",
    "title": "Minimal Editorial Object Posters",
    "prompt": "Minimal Editorial Object Posters",
    "stylePromptEn": "Minimal Editorial Object Posters",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-007",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/cinematic-wideangle-photos-2",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FLq1YMiyyRd4gGt7RI86P%2Fresized%2F1781009571352d_500x500.webp",
    "title": "Cinematic Wideangle Photos",
    "prompt": "Cinematic Wideangle Photos",
    "stylePromptEn": "Cinematic Wideangle Photos",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-008",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/pencil-drawings-sketching-lives",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FOFcORNvxWfMigPPxwNmx%2Fresized%2F1756553380636h_500x500.webp",
    "title": "Coloring Pages For Adults",
    "prompt": "Coloring Pages For Adults",
    "stylePromptEn": "Coloring Pages For Adults",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-009",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/ultrarealistic-floating-bottles",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FOWGt84JIwHvq3BJXvoz3%2Fresized%2F1752074121286z_500x500.webp",
    "title": "Ultrarealistic Floating Bottles",
    "prompt": "Ultrarealistic Floating Bottles",
    "stylePromptEn": "Ultrarealistic Floating Bottles",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-010",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/free-midnight-reveries",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FGwfQeXzRtqCzeca1nT31%2Fresized%2F1757676160946h_500x500.webp",
    "title": "Free Midnight Reveries",
    "prompt": "Free Midnight Reveries",
    "stylePromptEn": "Free Midnight Reveries",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-011",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/cinematic-lifestyle-portrait-photos-2",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FkAPZbQIGNAcQVJa5gafp%2Fresized%2F1769535199364c_500x500.webp",
    "title": "Cinematic Lifestyle Portrait Photos",
    "prompt": "Cinematic Lifestyle Portrait Photos",
    "stylePromptEn": "Cinematic Lifestyle Portrait Photos",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-012",
    "group": "行业品类",
    "subcategory": "服装",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/oversized-tshirt-and-hoodie-mockups-2",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FNaX4ONudVicXauUoxcZh%2Fresized%2F1777739625417_500x500.webp",
    "title": "Oversized Tshirt And Hoodie Mockups",
    "prompt": "Oversized Tshirt And Hoodie Mockups",
    "stylePromptEn": "Oversized Tshirt And Hoodie Mockups",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-013",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/kinetic-art-nouveau-artworks-2",
    "imageUrl": "https://assets.promptbase.com/DALLE_IMAGES%2FlLlawp7sYHOc3xML1JtYoJ6AoSy1%2Fresized%2F1725316673075_500x500.webp",
    "title": "Kinetic Art Nouveau Artworks",
    "prompt": "Kinetic Art Nouveau Artworks",
    "stylePromptEn": "Kinetic Art Nouveau Artworks",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-014",
    "group": "品牌商业",
    "subcategory": "营销活动",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/summer-travel-influencer-instagram-photos",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2Fy5tdy7VKsXXVwD18gJzU%2Fresized%2F1777922112999q_500x500.webp",
    "title": "Summer Travel Influencer Instagram Photos",
    "prompt": "Summer Travel Influencer Instagram Photos",
    "stylePromptEn": "Summer Travel Influencer Instagram Photos",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-015",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/create-visually-engaging-handdrawns",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2Fllko7NAGoP40lgrc1if6%2Fresized%2F1782723228134_500x500.webp",
    "title": "Create Visually Engaging Handdrawns",
    "prompt": "Create Visually Engaging Handdrawns",
    "stylePromptEn": "Create Visually Engaging Handdrawns",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-016",
    "group": "人物角色",
    "subcategory": "AI角色设",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/cute-minimalist-line-art-characters",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FylxpDmrgmmnMbFxMgM9R%2Fresized%2F1782754410509u_500x500.webp",
    "title": "Cute Minimalist Line Art Characters",
    "prompt": "Cute Minimalist Line Art Characters",
    "stylePromptEn": "Cute Minimalist Line Art Characters",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-017",
    "group": "行业品类",
    "subcategory": "美食饮品",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/professional-culinary-recipe-infographics-3",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FVizttQaFI8iWWiCYg5lH%2Fresized%2F1782683373730_500x500.webp",
    "title": "Professional Culinary Recipe Infographics",
    "prompt": "Professional Culinary Recipe Infographics",
    "stylePromptEn": "Professional Culinary Recipe Infographics",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-018",
    "group": "人物角色",
    "subcategory": "AI角色设",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/storybook-vintage-animal-cliparts",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FLQDq3tnw5LCdYGmF0Xq7%2Fresized%2F1782581835186z_500x500.webp",
    "title": "Storybook Vintage Animal Cliparts",
    "prompt": "Storybook Vintage Animal Cliparts",
    "stylePromptEn": "Storybook Vintage Animal Cliparts",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-019",
    "group": "行业品类",
    "subcategory": "教育",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/bold-red-editorial-infographics",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FPxyjDnYI4fTl10grhKNJ%2Fresized%2F1782732366448h_500x500.webp",
    "title": "Bold Red Editorial Infographics",
    "prompt": "Bold Red Editorial Infographics",
    "stylePromptEn": "Bold Red Editorial Infographics",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-020",
    "group": "品牌商业",
    "subcategory": "营销活动",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/summer-kids-doodle-collage-posters",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FCrKL2F5uxQ2t2h4OjZ93%2Fresized%2F1782672078319v_500x500.webp",
    "title": "Summer Kids Doodle Collage Posters",
    "prompt": "Summer Kids Doodle Collage Posters",
    "stylePromptEn": "Summer Kids Doodle Collage Posters",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-021",
    "group": "图形技法",
    "subcategory": "铅笔线描",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/doodle-story-collage-generator-2",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2F85sKiv3hxIYdM9ExYfXy%2Fresized%2F1782641029791y_500x500.webp",
    "title": "Doodle Story Collage Generator",
    "prompt": "Doodle Story Collage Generator",
    "stylePromptEn": "Doodle Story Collage Generator",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-022",
    "group": "行业品类",
    "subcategory": "教育",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/editorial-sketchnote-infographic-packs",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FaZ5K03QKNxPB2e8RUtB0%2Fresized%2F1782705977584b_500x500.webp",
    "title": "Editorial Sketchnote Infographic Packs",
    "prompt": "Editorial Sketchnote Infographic Packs",
    "stylePromptEn": "Editorial Sketchnote Infographic Packs",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-023",
    "group": "行业品类",
    "subcategory": "教育",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/handdrawn-sketchnote-learning-posters-2",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FouASP220jLRalxo5Odkn%2Fresized%2F1782706711572p_500x500.webp",
    "title": "Handdrawn Sketchnote Learning Posters",
    "prompt": "Handdrawn Sketchnote Learning Posters",
    "stylePromptEn": "Handdrawn Sketchnote Learning Posters",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-024",
    "group": "图形技法",
    "subcategory": "铅笔线描",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/hand-drawn-doodle-sketchnotes",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FTmsXtCihkChKCCh51kuP%2Fresized%2F1782655691741p_500x500.webp",
    "title": "Hand Drawn Doodle Sketchnotes",
    "prompt": "Hand Drawn Doodle Sketchnotes",
    "stylePromptEn": "Hand Drawn Doodle Sketchnotes",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-025",
    "group": "品牌商业",
    "subcategory": "营销活动",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/usa-iconic-bridges-timeline-posters",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2F8QZU5r9B7RnPDhAvDRnd%2Fresized%2F1782688364727f_500x500.webp",
    "title": "Usa Iconic Bridges Timeline Posters",
    "prompt": "Usa Iconic Bridges Timeline Posters",
    "stylePromptEn": "Usa Iconic Bridges Timeline Posters",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-026",
    "group": "行业品类",
    "subcategory": "教育",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/cute-whiteboard-learning-posters",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FSpAjuSP4zbT4MU3TYaz9%2Fresized%2F1782671780185y_500x500.webp",
    "title": "Cute Whiteboard Learning Posters",
    "prompt": "Cute Whiteboard Learning Posters",
    "stylePromptEn": "Cute Whiteboard Learning Posters",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-027",
    "group": "行业品类",
    "subcategory": "美食饮品",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/professional-recipe-infographic-makers-10",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FspJeObaetBS5TMKQzVTE%2Fresized%2F1782641733078_500x500.webp",
    "title": "Professional Recipe Infographic Makers",
    "prompt": "Professional Recipe Infographic Makers",
    "stylePromptEn": "Professional Recipe Infographic Makers",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-028",
    "group": "行业品类",
    "subcategory": "服装",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/vintage-occult-zodiac-sign-tshirts",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2Fp7DtibC9xPBE6Z7sqqqC%2Fresized%2F1782593843412f_500x500.webp",
    "title": "Vintage Occult Zodiac Sign Tshirts",
    "prompt": "Vintage Occult Zodiac Sign Tshirts",
    "stylePromptEn": "Vintage Occult Zodiac Sign Tshirts",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-029",
    "group": "行业品类",
    "subcategory": "教育",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/creative-whiteboard-learning-guides",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FYQ4PfaJtlWobJx8ZGgGE%2Fresized%2F1782658858933z_500x500.webp",
    "title": "Creative Whiteboard Learning Guides",
    "prompt": "Creative Whiteboard Learning Guides",
    "stylePromptEn": "Creative Whiteboard Learning Guides",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-030",
    "group": "行业品类",
    "subcategory": "教育",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/iconic-tv-series-infographic-posters",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FWYqFqL7Qkg16On21UNpX%2Fresized%2F1780512667734t_500x500.webp",
    "title": "Iconic Tv Series Infographic Posters",
    "prompt": "Iconic Tv Series Infographic Posters",
    "stylePromptEn": "Iconic Tv Series Infographic Posters",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-031",
    "group": "人物角色",
    "subcategory": "AI角色设",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/playful-childrens-storybook-illustrations",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FhYBUlNLgOHbwagGa977U%2Fresized%2F1780941335278d_500x500.webp",
    "title": "Playful Childrens Storybook Illustrations",
    "prompt": "Playful Childrens Storybook Illustrations",
    "stylePromptEn": "Playful Childrens Storybook Illustrations",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-032",
    "group": "品牌商业",
    "subcategory": "营销活动",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/retro-mediterranean-folk-art-posters",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FxxVsQ6e2nNMyeijsTi3I%2Fresized%2F1778789075491_500x500.webp",
    "title": "Retro Mediterranean Folk Art Posters",
    "prompt": "Retro Mediterranean Folk Art Posters",
    "stylePromptEn": "Retro Mediterranean Folk Art Posters",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-033",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/summer-cottagecore-junk-journal-pages",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FIQLUFtLG1ShDT36z1QUl%2Fresized%2F1780344205325k_500x500.webp",
    "title": "Summer Cottagecore Junk Journal Pages",
    "prompt": "Summer Cottagecore Junk Journal Pages",
    "stylePromptEn": "Summer Cottagecore Junk Journal Pages",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-034",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/ultrarealistic-cinematic-movie-stills",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2Fk8lMlSwNEyNJ9qYMdbKb%2Fresized%2F1780562885138_500x500.webp",
    "title": "Ultrarealistic Cinematic Movie Stills",
    "prompt": "Ultrarealistic Cinematic Movie Stills",
    "stylePromptEn": "Ultrarealistic Cinematic Movie Stills",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-035",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/awkward-70s-glamour-portraits",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FqSU2f14PtXOy2hAifd4b%2Fresized%2F1779902798955c_500x500.webp",
    "title": "Awkward 70s Glamour Portraits",
    "prompt": "Awkward 70s Glamour Portraits",
    "stylePromptEn": "Awkward 70s Glamour Portraits",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-036",
    "group": "人物角色",
    "subcategory": "AI角色设",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/summer-daisy-character-junk-journal-pages",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FxOcYRb1CdyMh4XQZInox%2Fresized%2F1781547943090x_500x500.webp",
    "title": "Summer Daisy Character Junk Journal Pages",
    "prompt": "Summer Daisy Character Junk Journal Pages",
    "stylePromptEn": "Summer Daisy Character Junk Journal Pages",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-037",
    "group": "品牌商业",
    "subcategory": "营销活动",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/glitch-royalty-brutalist-posters-2",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FrEGkv5FhR0Pym3OMBeei%2Fresized%2F1778309125978k_500x500.webp",
    "title": "Glitch Royalty Brutalist Posters",
    "prompt": "Glitch Royalty Brutalist Posters",
    "stylePromptEn": "Glitch Royalty Brutalist Posters",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-038",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/fantasy-summer-symphony-junk-journals",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FwUAjXSvilG4tKDEmF3ZE%2Fresized%2F1782498581404h_500x500.webp",
    "title": "Fantasy Summer Symphony Junk Journals",
    "prompt": "Fantasy Summer Symphony Junk Journals",
    "stylePromptEn": "Fantasy Summer Symphony Junk Journals",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-039",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/cozy-christmas-junk-journal-ephemera",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2Fb50kKHoL2pcNxy2UrIBB%2Fresized%2F1781895362750k_500x500.webp",
    "title": "Cozy Christmas Junk Journal Ephemera",
    "prompt": "Cozy Christmas Junk Journal Ephemera",
    "stylePromptEn": "Cozy Christmas Junk Journal Ephemera",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-040",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/french-cottage-peony-junk-journal-pages",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2Fn2jyxKg0fj798Gh9UHFy%2Fresized%2F1780598223724b_500x500.webp",
    "title": "French Cottage Peony Junk Journal Pages",
    "prompt": "French Cottage Peony Junk Journal Pages",
    "stylePromptEn": "French Cottage Peony Junk Journal Pages",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-041",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/body-reshaping",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FWB121XQ82xKZesf222V7%2Fresized%2F1780183597357_500x500.webp",
    "title": "Body Reshaping",
    "prompt": "Body Reshaping",
    "stylePromptEn": "Body Reshaping",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-042",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/cinematic-couple-portraits-pro-2",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FLjo8w0GHSGEYcpNsTbpz%2Fresized%2F1781540044354_500x500.webp",
    "title": "Cinematic Couple Portraits Pro",
    "prompt": "Cinematic Couple Portraits Pro",
    "stylePromptEn": "Cinematic Couple Portraits Pro",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-043",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/vector-tshirt-designs-2",
    "imageUrl": "https://assets.promptbase.com/DALLE_IMAGES%2FxEiEXlReguavXl77rgXCELjTazu2%2Fresized%2F1703943903404_500x500.webp",
    "title": "Vector Silhouette T-shirt Designs",
    "prompt": "Vector Silhouette T-shirt Designs",
    "stylePromptEn": "Vector Silhouette T-shirt Designs",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-044",
    "group": "行业品类",
    "subcategory": "服装",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/fashionable-t-shirt-designs",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2F8TJtTh09xI1PV8VZl6Qi%2Fresized%2F1743810053847g_500x500.webp",
    "title": "Fashionable Tshirt Designs",
    "prompt": "Fashionable Tshirt Designs",
    "stylePromptEn": "Fashionable Tshirt Designs",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-045",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/fantasy-inspired-tarot-cards",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2Fhv9zIe4YhGrBgsoJlnPm%2Fresized%2F1743816943314m_500x500.webp",
    "title": "Fantasyinspired Major Arcana Tarot Card",
    "prompt": "Fantasyinspired Major Arcana Tarot Card",
    "stylePromptEn": "Fantasyinspired Major Arcana Tarot Card",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-046",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/cute-pastel-vectors-for-kids",
    "imageUrl": "https://assets.promptbase.com/DALLE_IMAGES%2FHayawxMYEGfZYtUO5XLvAvElejs1%2Fresized%2F1681679195591_500x500.webp",
    "title": "Minimal Pastel Vectors For Kids",
    "prompt": "Minimal Pastel Vectors For Kids",
    "stylePromptEn": "Minimal Pastel Vectors For Kids",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-047",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/new-fakemon-and-pokemon-designs",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2F8i2jBNdpLLHixvwks4CJ%2Fresized%2F1743042644219m_500x500.webp",
    "title": "New Fakemon And Pokemon Designs",
    "prompt": "New Fakemon And Pokemon Designs",
    "stylePromptEn": "New Fakemon And Pokemon Designs",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-048",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/celebrity-caricatures",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FhuuXdBKn7NgIU5BtllkR%2Fresized%2F1743816982871l_500x500.webp",
    "title": "Celebrity Caricatures",
    "prompt": "Celebrity Caricatures",
    "stylePromptEn": "Celebrity Caricatures",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-049",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/comic-book-panels-and-pages",
    "imageUrl": "https://assets.promptbase.com/DALLE_IMAGES%2FCOyYUQNQVVUjE5LmEffybusWRgA2%2Fresized%2F1710361480155_500x500.webp",
    "title": "Comic Book Panels And Pages",
    "prompt": "Comic Book Panels And Pages",
    "stylePromptEn": "Comic Book Panels And Pages",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-050",
    "group": "人物角色",
    "subcategory": "AI角色设",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/retro-anime-characters",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2FKLL1TgK1A1DdG4B1Stza%2Fresized%2F1743833060346x_500x500.webp",
    "title": "Retro Anime Characters",
    "prompt": "Retro Anime Characters",
    "stylePromptEn": "Retro Anime Characters",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-051",
    "group": "风格美术",
    "subcategory": "Vintage复古",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/painterly-retro-illustrations-minimalists",
    "imageUrl": "https://assets.promptbase.com/DALLE_IMAGES%2FDrlAY7QxLpebJSSUEITDK2YKu8D3%2Fresized%2F1691187828159_500x500.webp",
    "title": "Painterly Retro Illustrations Minimalists",
    "prompt": "Painterly Retro Illustrations Minimalists",
    "stylePromptEn": "Painterly Retro Illustrations Minimalists",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-052",
    "group": "品牌商业",
    "subcategory": "营销活动",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/three-tone-abstract-posters",
    "imageUrl": "https://assets.promptbase.com/DALLE_IMAGES%2FHayawxMYEGfZYtUO5XLvAvElejs1%2Fresized%2F1680039282515_500x500.webp",
    "title": "Three Tone Abstract Posters",
    "prompt": "Three Tone Abstract Posters",
    "stylePromptEn": "Three Tone Abstract Posters",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-053",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/monochromatic-studio-portrait-photos-2",
    "imageUrl": "https://assets.promptbase.com/Thumbnails%2F46eShR0SLLY72h5uzDr6%2Fresized%2F1756974589048k_500x500.webp",
    "title": "Monochromatic Studio Portrait Photos",
    "prompt": "Monochromatic Studio Portrait Photos",
    "stylePromptEn": "Monochromatic Studio Portrait Photos",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-054",
    "group": "人物角色",
    "subcategory": "AI角色设",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/dnd-pc-character-art-illustrations",
    "imageUrl": "https://assets.promptbase.com/DALLE_IMAGES%2FRYgWvdHg5dkzXBJvKqXL%2Fresized%2F1692723311241_500x500.webp",
    "title": "DnD Pc Character Art Illustrations",
    "prompt": "DnD Pc Character Art Illustrations",
    "stylePromptEn": "DnD Pc Character Art Illustrations",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-055",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/realistic-phone-selfies-for-social-media",
    "imageUrl": "https://assets.promptbase.com/DALLE_IMAGES%2Fk54G0HZpxFcZ5wuzpZO51jJMZ3A3%2Fresized%2F1704046037097_500x500.webp",
    "title": "Realistic Phone Selfies For Social Media",
    "prompt": "Realistic Phone Selfies For Social Media",
    "stylePromptEn": "Realistic Phone Selfies For Social Media",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-056",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/moodboards-for-any-kind-of-brand",
    "imageUrl": "https://assets.promptbase.com/DALLE_IMAGES%2FT2EWTAY44LOXYGVWJfSkStrDyIn1%2Fresized%2F1682751700757_500x500.webp",
    "title": "Moodboards For Any Kind Of Brand",
    "prompt": "Moodboards For Any Kind Of Brand",
    "stylePromptEn": "Moodboards For Any Kind Of Brand",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-057",
    "group": "品牌商业",
    "subcategory": "营销活动",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/fun-travel-maps-with-text",
    "imageUrl": "https://assets.promptbase.com/DALLE_IMAGES%2FHayawxMYEGfZYtUO5XLvAvElejs1%2Fresized%2F1703530793711_500x500.webp",
    "title": "Fun Travel Maps With Text Titles",
    "prompt": "Fun Travel Maps With Text Titles",
    "stylePromptEn": "Fun Travel Maps With Text Titles",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-058",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/2d-isometric-pixel-art-game-sprites",
    "imageUrl": "https://assets.promptbase.com/DALLE_IMAGES%2FHayawxMYEGfZYtUO5XLvAvElejs1%2Fresized%2F1703195945980_500x500.webp",
    "title": "2D Isometric Pixel Art Game Sprites",
    "prompt": "2D Isometric Pixel Art Game Sprites",
    "stylePromptEn": "2D Isometric Pixel Art Game Sprites",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-059",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/asian-art-t-shirt-designs",
    "imageUrl": "https://assets.promptbase.com/DALLE_IMAGES%2FHayawxMYEGfZYtUO5XLvAvElejs1%2Fresized%2F1680686090910_500x500.webp",
    "title": "Asian Art T-shirt Designs",
    "prompt": "Asian Art T-shirt Designs",
    "stylePromptEn": "Asian Art T-shirt Designs",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-060",
    "group": "其他分类",
    "subcategory": "其他",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/tabletop-game-terrain-maps-dnds",
    "imageUrl": "https://assets.promptbase.com/DALLE_IMAGES%2FKsAVBIkpTcKM9WmIfdKy%2Fresized%2F1693079610387_500x500.webp",
    "title": "Tabletop Game Terrain Maps DnDs",
    "prompt": "Tabletop Game Terrain Maps DnDs",
    "stylePromptEn": "Tabletop Game Terrain Maps DnDs",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-061",
    "group": "品牌商业",
    "subcategory": "营销活动",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/dreamscape-surreal-posters",
    "imageUrl": "https://assets.promptbase.com/DALLE_IMAGES%2FHayawxMYEGfZYtUO5XLvAvElejs1%2Fresized%2F1685487813785_500x500.webp",
    "title": "Dreamlike Surreal Posters",
    "prompt": "Dreamlike Surreal Posters",
    "stylePromptEn": "Dreamlike Surreal Posters",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  },
  {
    "id": "promptbase-062",
    "group": "品牌商业",
    "subcategory": "营销活动",
    "sourceSite": "PromptBase",
    "sourceUrl": "https://promptbase.com/prompt/pastel-travel-postage-stamps",
    "imageUrl": "https://assets.promptbase.com/DALLE_IMAGES%2FHayawxMYEGfZYtUO5XLvAvElejs1%2Fresized%2F1707344228489_500x500.webp",
    "title": "Pastel Travel Postage Stamps",
    "prompt": "Pastel Travel Postage Stamps",
    "stylePromptEn": "Pastel Travel Postage Stamps",
    "licenseNote": "public preview URL only; prompt marketplace item license must be verified before commercial use"
  }
];
